apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: meu-nginx-2
  name: meu-nginx-2
spec:
  containers:
  - image: nginx:latest
    name: meu-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
